### ISSUE TITLE
OpenSCM pythonic interface

### ISSUE THREAD

**Issue by swillner** [openclimatedata/openscm#105]
As discussed with @rgieseke a more pythonic view to the `Core` object and in particular the `ParameterSet`, i.e. relying on attributes rather than on functions such as `get_writable_view` would be desirable.
@znicholls @lewisjared Any wishes from the high-level API as that should rely on the mid-level/low-level API for timeframe and unit conversion as well as abstraction layer for communication with adapters.

**Comment by znicholls** [comment]
My feeling to date has been that once we get things setup, there will be little interaction with the low level API (everything will be with the high level and the models) and so I'm not too fussed (I think I've got my head around this views business). More pythonic API for the core will certainly make it easier for new developers.

**Comment by znicholls** [comment]
I have a converter from scmdataframes to Core in the `scmcallib` branch so I'd rather not have to re-write things to accomodate another level (although writing again would be pretty simple compared to writing the first time).

**Comment by swillner** [comment]
I think we should change the wording for these levels. Overall, I would say there should be the following ways (interfaces/access points/...) to use OpenSCM:

- The Core API (standardized to be language agnostic): ``Core`` class
- A pythonic API: ``OpenSCM`` class
- ``ScmDataFrame`` as a convenience data structure to use; especially for IO with the standard file formats
- Additional utilities such as ensemble running (``Ensemble`` class), plotting functions, ...

Then we could abandon "low-level"/"high-level" wording.
@znicholls If you think that makes some kind of sense I would open a PR with restructured documentation...

**Comment by znicholls** [comment]
To double check:

- adapters would only interact with `Core`?
- what is the difference between OpenSCM and ScmDataFrame? Data frames are Pythonic already

Would the workflow still be, user --> run --> ScmDataFrame --> Core --> Adapter --> Model --> Adapter --> Core --> ScmDataFrame --> user --> plotting

**Comment by swillner** [comment]
>     * adapters would only interact with `Core`?

Yes, ``Core`` handles adapters from the outside. Adapters only talk to the ``ParameterSet`` (as part of the Core API) they receive from ``Core``.

>     * what is the difference between OpenSCM and ScmDataFrame? Data frames are Pythonic already

``OpenSCM`` would do the running and setting of individual parameters (more conveniently/pythonic than ``ParameterSet``), ``ScmDataFrame`` would handle input/output data if the users prefers more of a table view and can be handed over to ``OpenSCM`` for running the model.

> Would the workflow still be, user --> run --> ScmDataFrame --> Core --> Adapter --> Model --> Adapter --> Core --> ScmDataFrame --> user --> plotting?

There would be different workflows depending on the user's needs regarding convenience vs efficiency.

**Comment by znicholls** [comment]
> `OpenSCM` would do the running and setting of individual parameters (more conveniently/pythonic than `ParameterSet`)

In my experience fiddling with this, I've always passed a `ParameterSet` to an `Adapter` directly and let the adapter work it out from there (see [here](https://github.com/openclimatedata/openscm/blob/scmcallib/openscm/__init__.py)) rather than going through either `Core` or `OpenSCM`.

The reason is that I've always wanted a single model (i.e. `Adapter`) instance. The reason for that is I can run in different scenarios and then change the parameters of the model for each run without the cost of spinning up new instances or setting the scenario up each time. I could use `Core` for each run. However, to avoid having each `Core` instance spin up a new model instance I'd have to pass my `Adapter` instance into the `Core` instance. This feels rather convoluted compared to just saying, `Adapter`, set your scenario (without spinning up the model again), set your parameters (without resetting the scenario), run. 

I do like having the `Adapter` return a `Core` instance as then the `Adapter` has to put all the run information (start time, end time, parameters) in one place. As I said, I just can't see how it's useful going the other way where you have a whole bunch of steps which you don't want to repeat each time.

**Comment by swillner** [comment]
@znicholls I think we are on the same page here:

- The ``Core`` class just wrapps a corresponding ``Adapter`` instance to be the interface for the user (who does not directly talk to an ``Adapter``). So it is for one model with an arbitraty number of runs. ``Core`` itself doesn't do much but ensure the ``Adapter`` is used correctly (could in principle be done be ``Adapter`` itself but eliminates the need of a user to create the correct ``Adapter`` instance in the first place).
- ``OpenSCM`` would just be a subclass of ``Core`` providing convenience functions for getting/setting parameters.
- An ``Ensemble`` instance could also directly talk to an ``Adapter``.

**Comment by swillner** [comment]
(just to make sure: with "Core API" I mean ``Core`` and ``ParameterSet`` classes plus all the parameter handling in that)

**Comment by znicholls** [comment]
Ok got it! Sounds gewd

**Comment by rgieseke** [comment]
What's the CODEOWNERS thing, is it for notifications?

**Comment by swillner** [comment]
@rgieseke When you have the time I would be happy to hear your thoughts about how such an interface would preferably look like

**Comment by swillner** [comment]
Replaced by #146
